### ISSUE TITLE
I have a problem with npm run watch

### ISSUE THREAD

**Issue by lyquocphong** [kulmann/moodle-mod_millionaire#18]
I have problem with web-dev-server. I can run my vue app in moodle only when run build, for run dev or run watch, there is error in console said that unexpected token in myapp-lazy so it due to requirejs will fail. Another problem is I am using moodle 3.9 and when disablecaching for js, it also give fail

GET http://localhost:8081/lib/requirejs.php/-1/block_mmpolku2/app-lazy.js net::ERR_ABORTED 500 (Internal Server Error)

**Comment by lyquocphong** [comment]
I face problem that I cannot build with dev or development so I cannot use Vue devtools

**Comment by kulmann** [comment]
Hey, I'd appreciate to answer questions about your application in your repository. ;-) Give me a link and I'll happily take a look at your code base. Without context it's hard to help out anyway.
