### ISSUE TITLE
Issues related to string translation

### ISSUE THREAD

**Issue by lyquocphong** [kulmann/moodle-mod_millionaire#19]
I have check the store and it use ajax service to get all string of one component. But if I want to get string from multiple component so how i can get it ? Have you ever try to use core/str to load string in component on mounted hook ?

**Comment by kulmann** [comment]
Hey, I'd appreciate to answer questions about your application in your repository. ;-) Give me a link and I'll happily take a look at your code base. Without context it's hard to help out anyway.
